AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Lambda function using lambdamux router

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  LambdamuxFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  LambdamuxAPI:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  LambdamuxFunction:
    Description: "Lambdamux Lambda Function ARN"
    Value: !GetAtt LambdamuxFunction.Arn
